### ISSUE TITLE
bc2pg - use BCDC API to define tables

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#108]
Types and comments are available via the Catalogue's api : 
https://catalogue.data.gov.bc.ca/api/3/action/package_search?q=res_extras_resource_storage_location:bc%20geographic%20warehouse

Rather than have ogr2ogr guess the types, we could translate the oracle types to postgres types to create a more precise copy. Even just including the comments would be useful.

Unfortunately the API does not provide any clues on the geometry types.

@newgraphenvironment

**Comment by smnorris** [comment]
If we can consistently build any table available via WFS via definitions in the catalogue API, there is potential to turf the `bc2pg` command entirely (or at least the `ogr2ogr` dependency). With table structure known we can load the json to a staging table in the db via `bcdata cat` then pull the json into the pre-defined table with sql. As per https://github.com/smnorris/fwapg/blob/main/Makefile#L83

**Comment by NewGraphEnvironment** [comment]
Cool.  Is `data_precision` something you expect might come along for the ride and if not is it crazy to consider appending them to the date stamp table to make them available for access downstream?

**Comment by smnorris** [comment]
Any column stored as oracle type `NUMBER` could be stored in the db as postgres type `NUMERIC` with the given precision. Users downstream can look at definition in the db, no need to store it in the date stamp table.

**Comment by smnorris** [comment]
This is fine for general purpose loads. Where we want to optimize we might want to look and see if the precision fits into `integer`, `bigint` etc.

**Comment by smnorris** [comment]
Nicest would be to create the output table with the definition provided by BCDC, then load responses directly into the database from Python via psycopg2 (probably inserting chunks with `execute_values`) https://www.psycopg.org/docs/extras.html#psycopg2.extras.execute_values

psycopg2 does not provide a simple method for dynamically creating tables though. sqlalchemy does it like this:
https://stackoverflow.com/questions/43721680/sqlalchemy-create-dynamic-tables-and-columns
https://github.com/sqlalchemy/sqlalchemy/discussions/7289#discussioncomment-1606411

Not sure it is worth re-inventing the wheel - we can just keep function as is, adding some "ALTER" statements to define the types and "COMMENTS" for the documentation.
