### ISSUE TITLE
✨ [Feature Request] Support general public access to BC Data Catalogue ✨

### ISSUE THREAD

**Issue by galenseilis** [smnorris/bcdata#190]
Hi `bcdata` Contributors,

Being able to access data from the BC Data Catalogue in Python is valuable, and this is just as true for non-spatial data as it is for spatial data.

While there is [R `bcdata`](https://bcgov.github.io/bcdata/index.html), as suggested on the README, this is less convenient for using pipeline tooling written in Python (e.g. [Kedro](https://docs.kedro.org/en/stable/index.html)). It means either calling R as a process outside the pipeline and pulling the data into the pipeline, or using a tool like `rpy2`. Either way you end up with additional IO overhead (either via files or between processes).

I know my colleagues and I would be grateful if Python's `bcdata` provided more general access to the BC Data Catalogue.

Thank you for considering this feature request.

**Comment by smnorris** [comment]
PRs are welcome!

Happy to add this feature but my work for the Province tends to be spatial - I have not had any reason to move beyond a WFS/WCS wrapper to date.

**Comment by smnorris** [comment]
I'd also be interested to know what the use case is. 

AFAIK non-spatial data is simple to download - direct links are available and can thus be scripted in Python via `requests` / `curl` etc.  From my point of view, if spatial data was similarly available this package would be retired.

**Comment by galenseilis** [comment]
I did not know that all non-spatial data had direct links available, and I agree that deprioritizes supporting this feature. 

The remaining thing that comes to mind is just having a consistent method for obtaining data from the BC data Catalogue, provided that it isn't [a foolish consistency](https://en.wikipedia.org/wiki/Wikipedia:Emerson_and_Wilde_on_consistency).

**Comment by smnorris** [comment]
> I did not know that all non-spatial data had direct links available, and I agree that deprioritizes supporting this feature.

I don't know about *all* but my presumption is most. Definitely a presumption though.

> The remaining thing that comes to mind is just having a consistent method for obtaining data from the BC data Catalogue, provided that it isn't [a foolish consistency](https://en.wikipedia.org/wiki/Wikipedia:Emerson_and_Wilde_on_consistency).

A Python interface to the BCDC API does seem useful - but unless you're keen to build it, that request is probably better directed to DataBC rather than to me 😆

**Comment by galenseilis** [comment]
> I don't know about _all_ but my presumption is most. Definitely a presumption though.

Got it. Thanks for the heads up. 

From what I have grabbed so far (data related to healthcare, forestry, and petroleum transport) your inference seems to agree with what I have seen. I am willing to go on the assumption the non-spatial data I need on the Data Catalogue is available via direct links until I find otherwise. I will play it by ear.
 
> A Python interface to the BCDC API does seem useful - but unless you're keen to build it, that request is probably better directed to DataBC rather than to me 😆

Ha! Fair enough. 

Thank you for considering this feature request.

**Comment by smnorris** [comment]
👍 

Note that the API's catalogue page does have a support request link:  https://catalogue.data.gov.bc.ca/dataset/bc-data-catalogue-api.
