### ISSUE TITLE
dump - default to BC Albers (or add the option)

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#210]
Responses are much quicker if made in the native CRS vs EPSG:4326.

**Comment by ateucher** [comment]
Interesting the size difference! Decimal precision when converted to 4326 may be really high? Is there a WFS parameter to control that?

**Comment by smnorris** [comment]
Good point - I'm not sure.

I recall noticing the speed difference in the past, and that the default is to return 3005. I thought switching to 4236 was a recent change with code cleanup in latest two releases.... but it looks like 3005 was only the default with my main usage - `bc2pg`.

I think I'll drop `SRSNAME` from the request parameters and reproject internally if required.
