### ISSUE TITLE
use id as default sortby column

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#57]
As per https://github.com/bcgov/bcdata/issues/76 - the first column in the source tables is not necessarily unique - sorting by this column can lead to missed/duplicated records in paginated requests. `bcdata info` does not include `id` in its report. Perhaps hard code `id` as the default key to sort on for paginated requests?

**Comment by smnorris** [comment]
No, `id` is not a sortable column. For data with more than 10k records, if the first column is not unique the user will just have to know which column to use. Perhaps `OBJECTID` is present in every layer?

**Comment by smnorris** [comment]
sortby order of precedence:
- use `--fid` when set with `bc2pg` 
- `OBJECTID` where present
- `SEQUENCE_ID` where no `OBJECTID`
- where none of above are present, default to first column (appears to only occur in `WHSE_FOREST_VEGETATION.VEG_COMP_LYR_R1_POLY`, that is likely better downloaded through other channels anyway)

**Comment by ateucher** [comment]
@smnorris `WHSE_FOREST_VEGETATION.VEG_COMP_LYR_R1_POLY` does have `OBJECT_ID` (note the underscore) - should probably be put in the list. Also `FEATURE_ID`? (https://github.com/bcgov/bcdata/issues/76)

**Comment by smnorris** [comment]
I saw that and I arbitrarily decided that I didn't want to support case by case matching beyond looking for `SEQUENCE_ID`, just because there are a bunch of those.
Since I almost always grab the entire table and load it to postgres, I do prefer to have a primary key. Because that is not published, I think my best bet is to look it up/take a wild guess and tell bcdata explicitly to use that column for sorting and indexing: 
`bcdata bc2pg WHSE.SOMETABLE --fid SOMETABLE_ID` 

Based on how `bcgov\bcdata` is looking, I can see that this load to postgres tool may be the only thing I'll want to maintain at some point. Perhaps the new distribution service may make it unnecessary too.

**Comment by ateucher** [comment]
It's a slippery slope indeed. I opted to try a few: https://github.com/bcgov/bcdata/blob/41c4294c740c9522147e11df3f4edeb1f6b86285/R/utils.R#L263-L271

`bc2pg` looks awesome. @boshek we should dig into that.

**Comment by smnorris** [comment]
Note that `bc2pg` is still a bit fragile for multi-page loads because it creates temp tables in the target schema. If something bails there are no cleanup methods - it is a mess to cleanup. Works well enough for me but it could be tidied up.  The performance benefit of writing to multiple tables is not as big as I'd hoped - because the connection generally is the bottleneck, writing all the data to a single table with multiple threads doesn't slow things down too much (db locks).
