### ISSUE TITLE
DEM resampling method

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#63]
We can request the DEM data from the WCS at any resolution we want.... but how does the data get downsampled from the source 25m raster? Is there an option we can provide to specify this?

**Comment by smnorris** [comment]
naturally the options are listed right in the describecoverage request:

https://delivery.openmaps.gov.bc.ca/om/wcs?service=WCS&version=1.0.0&request=DescribeCoverage&coverage=pub:bc_elevation_25m_bcalb

<wcs:supportedInterpolations default="nearest neighbor">
<wcs:interpolationMethod>nearest neighbor</wcs:interpolationMethod>
<wcs:interpolationMethod>bilinear</wcs:interpolationMethod>
<wcs:interpolationMethod>bicubic</wcs:interpolationMethod>
</wcs:supportedInterpolations>

**Comment by smnorris** [comment]
Fixed, but note these timings! 
Request the data at native resolution and resample locally for *much* better performance.
```
$ time bcdata dem --bounds "[1046891, 704778, 1055345, 709629]" -o dem25.tif

real	0m1.044s
user	0m0.563s
sys	0m0.087s

$ time bcdata dem --bounds "[1046891, 704778, 1055345, 709629]" -o dem50.tif --interpolation bilinear --resolution 50

real	1m46.839s
user	0m0.559s
sys	0m0.083s

$ time gdalwarp -r bilinear -tr 50 50 dem25.tif dem50gdal.tif
Creating output file that is 169P x 97L.
Processing dem25.tif [1/1] : 0Using internal nodata values (e.g. -32768) for image dem25.tif.
Copying nodata values from source dem25.tif to destination dem50gdal.tif.
...10...20...30...40...50...60...70...80...90...100 - done.

real	0m0.513s
user	0m0.060s
sys	0m0.058s
```

**Comment by wburt** [comment]
Note taken -  Thanks @smnorris !
