### ISSUE TITLE
bc2pg - add PROMOTE_TO_MULTI option

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#80]
`ften_road_section_lines_svw` fails to load because of mixed types:

```
Warning 1: Geometry to be inserted is of type Multi Line String, whereas the layer geometry type is Line String.
Insertion is likely to fail
ERROR 1: ERROR:  Geometry type (MultiLineString) does not match column type (LineString)

ERROR 1: INSERT command for new feature failed.
ERROR:  Geometry type (MultiLineString) does not match column type (LineString)
```

**Comment by NewGraphEnvironment** [comment]
`$ bc2pg WHSE_TERRESTRIAL_ECOLOGY.ERC_ECOSECTIONS_SP --promote_to_multi
Usage: bc2pg [OPTIONS] DATASET
Try 'bc2pg --help' for help.

Error: No such option: --promote_to_multi`


# packages in environment at /Users/airvine/miniconda3/envs/bcfishpass:
#
# Name                    Version                   Build  Channel
affine                    2.3.1              pyhd8ed1ab_0    conda-forge
aom                       3.3.0                h07bb92c_1    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
bcdata                    0.6.1                    pypi_0    pypi
blosc                     1.21.1               hd414afc_2    conda-forge
boost-cpp                 1.74.0               h3afdda6_7    conda-forge
branca                    0.5.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h1c322ee_7    conda-forge
brotli-bin                1.0.9                h1c322ee_7    conda-forge
brotlipy                  0.7.0           py39hb18efdd_1004    conda-forge
brunsli                   0.1                  h9f76cd9_0    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.18.1               h3422bc3_0    conda-forge
c-blosc2                  2.1.1                h10ebec7_0    conda-forge
ca-certificates           2021.10.8            h4653dfc_0    conda-forge
cairo                     1.16.0            h933af38_1010    conda-forge
certifi                   2021.10.8        py39h2804cbe_2    conda-forge
cffi                      1.15.0           py39h52b1de0_0    conda-forge
cfitsio                   4.1.0                hd4f5c17_0    conda-forge
charls                    2.3.4                hbdafb3b_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.1.3            py39h2804cbe_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
cryptography              36.0.2           py39hbe5e4b8_1    conda-forge
curl                      7.83.1               h2fcd78c_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.11.2           py39hb18efdd_2    conda-forge
dask-core                 2022.5.0           pyhd8ed1ab_0    conda-forge
expat                     2.4.8                h6b3803e_0    conda-forge
fiona                     1.8.21           py39hdccbba0_1    conda-forge
folium                    0.12.1.post1       pyhd8ed1ab_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               hfb34624_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.33.3           py39h9eb174b_0    conda-forge
freetype                  2.10.4               h17b34a0_1    conda-forge
freexl                    1.0.6                h27ca646_0    conda-forge
fsspec                    2022.3.0           pyhd8ed1ab_0    conda-forge
gdal                      3.4.3            py39h71aabf0_0    conda-forge
geoalchemy2               0.6.3                      py_0    conda-forge
geopandas                 0.10.2             pyhd8ed1ab_1    conda-forge
geopandas-base            0.10.2             pyha770c72_1    conda-forge
geos                      3.10.2               hbdafb3b_0    conda-forge
geotiff                   1.7.1                hdd9897c_1    conda-forge
gettext                   0.19.8.1          h049c9fb_1008    conda-forge
giflib                    5.2.1                h27ca646_2    conda-forge
greenlet                  1.1.2            py39h0ef5a74_2    conda-forge
hdf4                      4.2.15               h0ef36ac_3    conda-forge
hdf5                      1.12.1          nompi_hf9525e8_104    conda-forge
icu                       69.1                 hbdafb3b_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
imagecodecs               2022.2.22        py39hfa2e616_4    conda-forge
imageio                   2.19.1             pyhcf75d05_0    conda-forge
jbig                      2.1               h3422bc3_2003    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h1c322ee_1    conda-forge
jq                        1.6               h27ca646_1000    conda-forge
json-c                    0.16                 hc449e50_0    conda-forge
jxrlib                    1.1                  h27ca646_2    conda-forge
kealib                    1.4.14               h8a8d77f_3    conda-forge
kiwisolver                1.4.2            py39h2c803a9_1    conda-forge
krb5                      1.19.3               hf9b2bbe_0    conda-forge
lcms2                     2.12                 had6a04f_0    conda-forge
lerc                      3.0                  hbdafb3b_0    conda-forge
libaec                    1.0.6                hbdafb3b_0    conda-forge
libavif                   0.10.1               h1c322ee_0    conda-forge
libblas                   3.9.0           14_osxarm64_openblas    conda-forge
libbrotlicommon           1.0.9                h1c322ee_7    conda-forge
libbrotlidec              1.0.9                h1c322ee_7    conda-forge
libbrotlienc              1.0.9                h1c322ee_7    conda-forge
libcblas                  3.9.0           14_osxarm64_openblas    conda-forge
libcurl                   7.83.1               h2fcd78c_0    conda-forge
libcxx                    14.0.3               h6a5c8ee_0    conda-forge
libdap4                   3.20.6               h8510809_2    conda-forge
libdeflate                1.10                 h3422bc3_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgdal                   3.4.3                h5cd83ce_0    conda-forge
libgfortran               5.0.0.dev0      11_0_1_hf114ba7_23    conda-forge
libgfortran5              11.0.1.dev0         hf114ba7_23    conda-forge
libglib                   2.70.2               h67e64d8_4    conda-forge
libiconv                  1.16                 h642e427_0    conda-forge
libidn2                   2.3.2                h3422bc3_0    conda-forge
libkml                    1.3.0             h893ab4d_1014    conda-forge
liblapack                 3.9.0           14_osxarm64_openblas    conda-forge
libnetcdf                 4.8.1           nompi_h96a3436_102    conda-forge
libnghttp2                1.47.0               he723fca_0    conda-forge
libopenblas               0.3.20          openmp_h2209c59_0    conda-forge
libpng                    1.6.37               hf7e6567_2    conda-forge
libpq                     14.3                 h8ab49ba_0    conda-forge
librttopo                 1.1.0                h56e3e6d_9    conda-forge
libspatialindex           1.9.3                hbdafb3b_4    conda-forge
libspatialite             5.0.1               he30b116_15    conda-forge
libssh2                   1.10.0               hb80f160_2    conda-forge
libtiff                   4.3.0                h77dc3b6_3    conda-forge
libunistring              0.9.10               h3422bc3_0    conda-forge
libwebp                   1.2.2                h0d20362_0    conda-forge
libwebp-base              1.2.2                h3422bc3_1    conda-forge
libxcb                    1.13              h9b22ae9_1004    conda-forge
libxml2                   2.9.12               hedbfbf4_1    conda-forge
libzip                    1.8.0                h3887732_1    conda-forge
libzlib                   1.2.11            h90dfc92_1014    conda-forge
libzopfli                 1.0.3                h9f76cd9_0    conda-forge
llvm-openmp               14.0.3               hd125106_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4-c                     1.9.3                hbdafb3b_1    conda-forge
make                      4.3                  he57ea6c_1    conda-forge
mapclassify               2.4.3              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1            py39hb18efdd_1    conda-forge
matplotlib-base           3.5.2            py39h4ee150f_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
networkx                  2.8                pyhd8ed1ab_0    conda-forge
nspr                      4.32                 hbdafb3b_1    conda-forge
nss                       3.77                 h3fd8894_0    conda-forge
numpy                     1.22.3           py39h64940a9_2    conda-forge
oniguruma                 6.9.7.1              h3422bc3_0    conda-forge
openjpeg                  2.4.0                h062765e_1    conda-forge
openssl                   1.1.1o               ha287fd2_0    conda-forge
owslib                    0.25.0             pyhd8ed1ab_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.2            py39h2666b31_1    conda-forge
parallel                  20220222             hce30654_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 hbdafb3b_0    conda-forge
perl                      5.32.1          2_h9b22ae9_perl5    conda-forge
pillow                    9.1.0            py39hd72dd6b_2    conda-forge
pip                       22.1               pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h27ca646_0    conda-forge
poppler                   22.04.0              hb0e405e_0    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                9.6.6                h65cfe13_1  
proj                      9.0.0                hb719e4a_1    conda-forge
psycopg2                  2.9.3            py39h082f845_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyproj                    3.3.1            py39h2816e27_0    conda-forge
pysocks                   1.7.1            py39h2804cbe_5    conda-forge
python                    3.9.12          hfc7342c_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pywavelets                1.3.0            py39h43ea957_1    conda-forge
pyyaml                    6.0              py39hb18efdd_4    conda-forge
rasterio                  1.2.10           py39h4f00f16_5    conda-forge
rasterstats               0.16.0             pyhd8ed1ab_0    conda-forge
readline                  8.1                  hedafd6a_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
rtree                     1.0.0            py39hb28b0e7_1    conda-forge
scikit-image              0.19.2           py39h7f752ed_0    conda-forge
scikit-learn              1.1.0            py39h255bef5_0    conda-forge
scipy                     1.8.0            py39h5060c3b_1    conda-forge
setuptools                62.2.0           py39h2804cbe_0    conda-forge
shapely                   1.8.2            py39hb53f2e7_1    conda-forge
simplejson                3.17.6           py39hb18efdd_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                h39c3846_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sqlalchemy                1.4.36           py39h9eb174b_0    conda-forge
sqlite                    3.38.5               h40dfcc0_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tifffile                  2022.5.4           pyhd8ed1ab_0    conda-forge
tiledb                    2.8.3                hdd33e7b_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
unicodedata2              14.0.0           py39hb18efdd_1    conda-forge
unzip                     6.0                  h3422bc3_3    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wget                      1.20.3               hb616509_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                hff64b9e_4    conda-forge
xorg-libxau               1.0.9                h27ca646_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xyzservices               2022.4.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zfp                       0.5.5                hcfdfaf5_8    conda-forge
zip                       3.0                  h27ca646_1    conda-forge
zlib                      1.2.11            h90dfc92_1014    conda-forge
zlib-ng                   2.0.6                he4db4b2_0    conda-forge
zstd                      1.5.2                h861e0a7_0    conda-forge

**Comment by NewGraphEnvironment** [comment]
hmmm. maybe not really the issue.

`bc2pg WHSE_TERRESTRIAL_ECOLOGY.ERC_ECOSECTIONS_SP
Usage: bc2pg [OPTIONS] DATASET
Try 'bc2pg --help' for help.

Error: Invalid value for '--email': Provide --email or set $BCDATA_EMAIL`

**Comment by smnorris** [comment]
Email shouldn’t be required, that was removed some time ago. Try upgrading?

**Comment by NewGraphEnvironment** [comment]
was running into

```
$ bc2pg WHSE_TERRESTRIAL_ECOLOGY.ERC_ECOSECTIONS_SP
Traceback (most recent call last):
  File "/Users/airvine/miniconda3/bin/bc2pg", line 5, in <module>
    from pgdata.cli import cli
  File "/Users/airvine/miniconda3/lib/python3.9/site-packages/pgdata/__init__.py", line 9, in <module>
    from pgdata.database import Database
  File "/Users/airvine/miniconda3/lib/python3.9/site-packages/pgdata/database.py", line 17, in <module>
    from .util import row_type
  File "/Users/airvine/miniconda3/lib/python3.9/site-packages/pgdata/util.py", line 3, in <module>
    from six import string_types
ModuleNotFoundError: No module named 'six'
```
so tried `pip unistall six` and `pip install six` to no avail... 

Next did a fresh clone of the repo and install via `conda env create -f environment.yml` with correct configuration appended to the bottomof the `.yml`

`variables:
  PGHOST: localhost
  PGUSER: postgres
  PGPORT: 5432
  PGDATABASE: bcfishpass
  DATABASE_URL: postgresql://postgres@localhost:5432/bcfishpass`

Still getting the same response

```
(bcdataenv) 
airvine at Allans-MacBook-Pro in ~/Projects/repo/bcdata on master
$ bc2pg REG_LEGAL_AND_ADMIN_BOUNDARIES.QSOI_BC_REGIONS
Traceback (most recent call last):
  File "/Users/airvine/miniconda3/bin/bc2pg", line 5, in <module>
    from pgdata.cli import cli
  File "/Users/airvine/miniconda3/lib/python3.9/site-packages/pgdata/__init__.py", line 9, in <module>
    from pgdata.database import Database
  File "/Users/airvine/miniconda3/lib/python3.9/site-packages/pgdata/database.py", line 17, in <module>
    from .util import row_type
  File "/Users/airvine/miniconda3/lib/python3.9/site-packages/pgdata/util.py", line 3, in <module>
    from six import string_types
ModuleNotFoundError: No module named 'six'
```
Never did get the BEC download to work a couple weeks ago as it had this same `six` error.  Any chance you might test to see if you get the same result?  Thought about moving to new issue but figured I was cluttering your issue logs enough these days and was related so left here.  Thanks Simon.  As you should know, this tool is absolutely indispensable and incredible. Thank you.

**Comment by smnorris** [comment]
Looks to me like you're still using an old version. 
Try this:
```
$ python
Python 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:27:43)
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bcdata
>>> bcdata.__version__
'0.5.1'
```

**Comment by NewGraphEnvironment** [comment]
I had just cloned the repo this am though...

Gave it a try.  maybe I should have been in a new env?

```
(bcdataenv) 
airvine at Allans-MacBook-Pro in ~/Projects/repo/bcdata on master [!]
$ python
Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:42:03) [Clang 12.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bcdata
>>> bcdata.__version__
'0.6.2dev0'
>>> exit()
(bcdataenv) 
airvine at Allans-MacBook-Pro in ~/Projects/repo/bcdata on master [!]
$ bc2pg REG_LEGAL_AND_ADMIN_BOUNDARIES.QSOI_BC_REGIONS
Traceback (most recent call last):
  File "/Users/airvine/miniconda3/bin/bc2pg", line 5, in <module>
    from pgdata.cli import cli
  File "/Users/airvine/miniconda3/lib/python3.9/site-packages/pgdata/__init__.py", line 9, in <module>
    from pgdata.database import Database
  File "/Users/airvine/miniconda3/lib/python3.9/site-packages/pgdata/database.py", line 17, in <module>
    from .util import row_type
  File "/Users/airvine/miniconda3/lib/python3.9/site-packages/pgdata/util.py", line 3, in <module>
    from six import string_types
ModuleNotFoundError: No module named 'six'
```

**Comment by smnorris** [comment]
yeah, something odd is going on. If you're getting that in a fresh clone it probably isn't packaging but I've created a new issue. If you can revert to 0.5.1 that should work.

**Comment by smnorris** [comment]
what is the result of `which bcdata bc2pg` or `which bcdata` ?

**Comment by smnorris** [comment]
closing in favour of #100
